### ISSUE TITLE
veracrypt-1.24-Hotfix1 fails to build on linux

### ISSUE THREAD

**Issue by david-geiger** [veracrypt/VeraCrypt#529]
Hi,

latest release fails to build on Mageia Cauldron with:

/home/iurt/rpmbuild/BUILD/VeraCrypt-VeraCrypt_1.24-Hotfix1/src/Crypto/jitterentropy-base-user.h:52:16: error: conflicting declaration 'typedef uint64 __u64'

[veracrypt_build_log.log](https://github.com/veracrypt/VeraCrypt/files/3777501/veracrypt_build_log.log)

Regards,
David

**Comment by idrassi** [comment]
Hi,

It looks like __u64 is already defined under Mageia but not on other distributions.
The fix is easy: just remove this line and replace all occurrences of __u64 by uint64.

I can push a commit for this but it would be helpful if you can first check that it works this way and maybe you could create a pull request for it.

**Comment by david-geiger** [comment]
Hmmm it build on Mageia7 with GCC 8.3.1 but not on Cauldron with GCC 9.2.1, could it be the that?

**Comment by david-geiger** [comment]
Also note that veracrypt 1.24 build fine on Cauldron, just the hotfix1 who doesn't build.

**Comment by idrassi** [comment]
I have pushed a commit that should fix this error: https://github.com/veracrypt/VeraCrypt/commit/3fa636d477119fff6e372074568edb42d038f508

Can you pleas try it and report the result?
I think that indeed the issue is caused by gcc 9 usage.

**Comment by david-geiger** [comment]
hmmm now it fails on aarch64 with:

> In file included from ../Crypto/jitterentropy.h:47,
                 from ../Crypto/jitterentropy-base.c:67:
../Crypto/jitterentropy-base.c: In function 'jent_loop_shuffle':
../Crypto/jitterentropy-base-user.h:92:2: error: impossible constraint in 'asm'
   92 |  asm volatile("rdtsc" : EAX_EDX_RET(val, low, high));
      |  ^~~
make[1]: *** [/home/iurt/rpmbuild/BUILD/VeraCrypt-VeraCrypt_1.24-Hotfix1/src/Build/Include/Makefile.inc:25: ../Crypto/jitterentropy-base.o0] Error 1
make[1]: Leaving directory '/home/iurt/rpmbuild/BUILD/VeraCrypt-VeraCrypt_1.24-Hotfix1/src/Volume'
make[1]: *** Waiting for unfinished jobs....

**Comment by david-geiger** [comment]
Same error on armv7h.

**Comment by idrassi** [comment]
I have pushed a commit that should fix both failure: https://github.com/veracrypt/VeraCrypt/commit/afe6b2f45b15393026a1159e5f3d165ac7d0b94a

Before this commit, the code always expected an x86/x86-64 platform.

**Comment by david-geiger** [comment]
Excellent! now it build fine on all arches...
Thanks

**Comment by idrassi** [comment]
Thank you for the confirmation.
