### ISSUE TITLE
Ubuntu 22.04 (build env) depecation.  plus on Ubuntu 26.04:  error: implicit declaration of function ‘BLAKE2_ROUND’

### ISSUE THREAD

**Issue by JamesParrott** [veracrypt/VeraCrypt#1871]
Hi everyone,

Thanks for making, and maintaining, such an amazing, import tool.  

I want to point out that I fully appreciate, that users should not expect free technical support, to compile Veracrypt on any random platform, with any random custom environment changes, they wish.  Veracrypt compiles on Ubuntu 22.04, and .deb packages etc. are provided.

However, compiling on multiple platforms can shine a light on potential areas for improvement, and in this particular case [Ubuntu 22.04 is scheduled for EOL this April year](https://documentation.ubuntu.com/release-notes/22.04/#support-lifespan) by canonical, and [Github](https://github.com/actions/runner-images/issues/14254) have scheduled deprecation to start 10 days from now, on September 17th.

So specifically, I naively tried to [bump the build runner to Ubuntu 26.04](https://github.com/JamesParrott/VeraCrypt/actions/runs/34131647210/job/101772927978), and got the following error:

```
Compiling argon2.c
Compiling core.c
Compiling opt_sse2.c
../Crypto/Argon2/src/opt_sse2.c: In function ‘fill_block’:
../Crypto/Argon2/src/opt_sse2.c:61:9: error: implicit declaration of function ‘BLAKE2_ROUND’; did you mean ‘BLAKE2_ROUND_1’? [-Wimplicit-function-declaration]
   61 |         BLAKE2_ROUND(state[8 * i + 0], state[8 * i + 1], state[8 * i + 2],
      |         ^~~~~~~~~~~~
      |         BLAKE2_ROUND_1
make[1]: *** [/home/runner/work/VeraCrypt/VeraCrypt/src/Build/Include/Makefile.inc:21: ../Crypto/Argon2/src/opt_sse2.o] Error 1
make: *** [Makefile:705: all] Error 2

```

I haven't dug into this deeply, as some of you will  know far more about the build process than I do.  The define is there, so it's probably just due to a breaking change in a dependency, or a change in a newer version of gcc, e.g. how the pre-processor `#defines` priority order.  Either that or some other tweak to the config or CMake is required, (that I should've made and didn't).  So I'm just raising this right now for awareness.  

It'd be good for everyone in the long term, to have it sorted out, so we're not relying on building Veracrypt on an unsupported distro version.

James.

**Comment by JamesParrott** [comment]
Good news everyone!  

Veracrypt does build on a Ubuntu 24.04 runner [just fine](https://github.com/JamesParrott/VeraCrypt/actions/runs/34135238126)

By the way, if for whatever reason, it was decided to stick with Ubuntu 22.04 (regardless of the lack of support), then perhaps a slightly more reproducible build than relying on a Github Actions runner image is to use a Docker-containerised action?:

```yml

jobs:
  test:
    runs-on: ubuntu-latest # host OS that runs Docker

    container:
      image: ubuntu:22.04
```

In my experience, there's still a lot of work to do though, to customise the standard Ubuntu Docker images, to have everything installed that Github Actions runner images have out of the box.

**Comment by JamesParrott** [comment]
[These](https://launchpadlibrarian.net/865148952/buildlog_ubuntu-resolute-ppc64el.veracrypt_1.26.29-0vanir1~bpo26.04_BUILDING.txt.gz) are the logs from Unit193's build of Veracypt, on Ubuntu 26.04.


```
Format: 1.0
Source: veracrypt
Binary: veracrypt veracrypt-dbgsym
Architecture: ppc64el
Version: 1.26.29-0vanir1~bpo26.04
Checksums-Md5:
 2d17e03f64a289345cb55f2ef8cc3450 16966498 veracrypt-dbgsym_1.26.29-0vanir1~bpo26.04_ppc64el.ddeb
 4d0cbb32d8d0998efce4d17cc138f40f 8712806 veracrypt_1.26.29-0vanir1~bpo26.04_ppc64el.deb
Checksums-Sha1:
 319f2a68f46b4138cb76c0e5314b9766bf04e70c 16966498 veracrypt-dbgsym_1.26.29-0vanir1~bpo26.04_ppc64el.ddeb
 37767b252bbb44c03e6cc35d6421dc6bb9d4f7e3 8712806 veracrypt_1.26.29-0vanir1~bpo26.04_ppc64el.deb
Checksums-Sha256:
 1d7b392c03b6cb49fff4af400cce2b5c2f881696413ccc0eecd13cb7da1d45a4 16966498 veracrypt-dbgsym_1.26.29-0vanir1~bpo26.04_ppc64el.ddeb
 6678d1be3e7b30e79bba3edf39b0f487905acfefee9b24251f0a02601d60d0ad 8712806 veracrypt_1.26.29-0vanir1~bpo26.04_ppc64el.deb
Build-Origin: Ubuntu
Build-Architecture: ppc64el
Build-Date: Mon, 15 Jun 2026 10:03:00 +0000
Build-Path: /build/veracrypt-bmfiLz/veracrypt-1.26.29
Build-Tainted-By:
 usr-local-has-programs
Installed-Build-Depends:
 adduser (= 3.153ubuntu1),
 adwaita-icon-theme (= 50.0-1),
 at-spi2-common (= 2.60.0-1),
 autoconf (= 2.72-3.1ubuntu2),
 automake (= 1:1.18.1-3build1),
 autopoint (= 0.23.2-1),
 autotools-dev (= 20240727.1build1),
 base-files (= 14ubuntu6.1),

...




 sysvinit-utils (= 3.15-5ubuntu1),
 tar (= 1.35+dfsg-4),
 tzdata (= 2026a-3ubuntu1),
 util-linux (= 2.41.3-3ubuntu2),
 uuid-dev (= 2.41.3-3ubuntu2),
 wayland-protocols (= 1.47-1),
 wx-common (= 3.2.9+dfsg-1),
 wx3.2-headers (= 3.2.9+dfsg-1),
 x11-common (= 1:7.7+26ubuntu1),
 x11proto-dev (= 2025.1-1),
 xkb-data (= 2.46-2),
 xml-core (= 0.19build1),
 xorg-sgml-doctools (= 1:1.11-1.1build1),
 xtrans-dev (= 1.6.0-1build1),
 xz-utils (= 5.8.3-1),
 zlib1g (= 1:1.3.dfsg+really1.3.1-1ubuntu3),
 zlib1g-dev (= 1:1.3.dfsg+really1.3.1-1ubuntu3)
Environment:
 DEB_BUILD_OPTIONS="parallel=4"
 DEB_BUILD_PROFILES="derivative.ubuntu noudeb"
 LANG="C.UTF-8"
 LC_COLLATE="C.UTF-8"
 LC_CTYPE="C.UTF-8"
 SOURCE_DATE_EPOCH="1781517193"

```

[https://launchpadlibrarian.net/865149175/veracrypt_1.26.29-0vanir1~bpo26.04_ppc64el.buildinfo](https://launchpadlibrarian.net/865149175/veracrypt_1.26.29-0vanir1~bpo26.04_ppc64el.buildinfo)
