### ISSUE TITLE
MacOS build fails.

### ISSUE THREAD

**Issue by euakll** [veracrypt/VeraCrypt#828]
When you clone the repository and try to build on MacOS 10.15.7 (x86) you get an error during building.

# Expected behavior
The build is successfull.

# Observed behavior
```
Compiling Buffer.cpp
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk' [-Wmissing-sysroot]
In file included from Buffer.cpp:13:
In file included from ./Buffer.h:16:
In file included from ./PlatformBase.h:17:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/list:183:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:653:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeinfo:60:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/exception:81:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstdlib:85:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:97:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
make[1]: *** [Buffer.o] Error 1
make: *** [all] Error 2
```

# Steps to reproduce
`git clone https://github.com/veracrypt/VeraCrypt.git`
`cd VeraCrypt/src`
`make`

# Your Environment
MacOS 10.15.7 (x86)
Installed all requirements.

**Comment by idrassi** [comment]
What is the version of Xcode installed on your machine?

The SDK version to use depends on the Xcode version installed on your machine You should check which version of SDK has installed by Xcode on your machine. The quickest way is to navigate to "`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs`"' in Terminal and use "`ls`" command to list available SDKs. 

Also, as indicated in the readme, you can look at [build_veracrypt_macosx.sh](https://github.com/veracrypt/VeraCrypt/blob/master/src/Build/build_veracrypt_macosx.sh) available under "[src/Build](https://github.com/veracrypt/VeraCrypt/tree/master/src/Build)" to see how a full build is performed, especially the use of VC_OSX_SDK if you want to target a version of macOS different from the SDK available.
